CREATE SCHEMA `my_movie` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `my_movie`.`USER` (
  `U_ID` VARCHAR(20) NOT NULL,
  `U_Password` VARCHAR(20) NOT NULL,
  `U_Name` VARCHAR(20) NOT NULL,
  `U_Sex` TINYINT NULL,
  `U_Birth` DATE NULL,
  `U_Email` VARCHAR(30) NULL,
  `U_Time` INT NOT NULL,
  PRIMARY KEY (`U_ID`));

CREATE TABLE `my_movie`.`MOVIE` (
  `M_ID` CHAR(5) NOT NULL,
  `M_Name` VARCHAR(30) NOT NULL,
  `M_Director` VARCHAR(20) NULL,
  `M_Poster` VARCHAR(500) NULL,
  `M_RelYear` INT NULL,
  `M_Rank` TINYINT NULL,
  `M_RunningTime` INT NOT NULL,
  `M_AvgGrade` FLOAT NOT NULL,
  PRIMARY KEY (`M_ID`));

CREATE TABLE `my_movie`.`GENRE` (
  `G_ID` CHAR(5) NOT NULL,
  `G_Category` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`G_ID`));

CREATE TABLE `my_movie`.`INTEREST` (
  `U_ID` VARCHAR(20) NOT NULL,
  `G_ID` CHAR(5) NOT NULL,
  PRIMARY KEY (`U_ID`, `G_ID`),
  CONSTRAINT `I_U_ID`
    FOREIGN KEY (`U_ID`)
    REFERENCES `my_movie`.`USER` (`U_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `I_G_ID`
    FOREIGN KEY (`G_ID`)
    REFERENCES `my_movie`.`GENRE` (`G_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `my_movie`.`BELONG` (
  `M_ID` CHAR(5) NOT NULL,
  `G_ID` CHAR(5) NOT NULL,
  PRIMARY KEY (`M_ID`, `G_ID`),
  CONSTRAINT `B_M_ID`
    FOREIGN KEY (`M_ID`)
    REFERENCES `my_movie`.`MOVIE` (`M_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `B_G_ID`
    FOREIGN KEY (`G_ID`)
    REFERENCES `my_movie`.`GENRE` (`G_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `my_movie`.`RECORD` (
  `U_ID` VARCHAR(20) NOT NULL,
  `M_ID` CHAR(5) NOT NULL,
  `R_Date` DATE NOT NULL,
  `R_One_Eval` VARCHAR(100) NULL,
  `R_Eval` VARCHAR(1000) NULL,
  `R_Grade` FLOAT NOT NULL,
  PRIMARY KEY (`U_ID`, `M_ID`),
  CONSTRAINT `R_U_ID`
    FOREIGN KEY (`U_ID`)
    REFERENCES `my_movie`.`USER` (`U_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `R_M_ID`
    FOREIGN KEY (`M_ID`)
    REFERENCES `my_movie`.`MOVIE` (`M_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
